const Data = [
  { Img: "movie/AVENGERS ENDGAME.jpg",
  Name: "AVENGERS ENDGAME",
  star: "8.4/10  ⭐",
  rotten: "94% 🍅",
  link: "",
},
{
  Img: "movie/AVENGERS INFINITY WAR.jpg",
  Name: "AVENGERS INFINITY WAR",
  star: "8.4/10  ⭐",
  rotten: "85% 🍅",
  link: "",
},{
    Img: "movie/AVENGERS.jpg",
    Name: "AVENGERS",
    star: "8.0/10  ⭐",
    rotten: "96% 🍅",
    link: "",
  },
  {
    Img: "movie/BATNAN BEGINS.jpg",
    Name: "BATMAN BEGINS",
    star: "8.2/10  ⭐",
    rotten: "84% 🍅",
    link: "",
  },
  {
    Img: "movie/IRON MAN 1.jpg",
    Name: "IRON MAN 1",
    star: "7.9/10 ⭐",
    rotten: "94% 🍅",
    link: "",
  },
  {
    Img: "movie/JOHN WICK 1.jpg",
    Name: "JOHN WICK",
    star: "7.4/10  ⭐",
    rotten: "86% 🍅",
    link: "",
  },
  {
    Img: "movie/THE DARK KNIGHT.jpg",
    Name: "THE DARK KNIGHT",
    star: "9.0/10  ⭐",
    rotten: "94% 🍅",
    link: "",
  },
  {
    Img: "movie/WALL-E.jpg",
    Name: "WALLE-E",
    star: "8.4/10 ⭐",
    rotten: "95% 🍅",
    link: "",
  },
  {
    Img: "movie/BLACK PANTHER.jpg",
    Name: "BLACK PANTHER ",
    star: "7.3/10 ⭐",
    rotten: "96% 🍅",
    link: "",
  },
  {
    Img: "movie/IT CHAPTER 1.jpg",
    Name: "IT CHAPTER 1",
    star: "7.3/10 ⭐",
    rotten: "86% 🍅",
    link: "",
  },
  {
    Img: "movie/THE DARK KNIGHT RISES.jpg",
    Name: "THE DARK KNIGHT RISES",
    star: "8.4/10 ⭐",
    rotten: "87% 🍅",
    link: "",
  },
  {
    Img: "movie/JOHN WICK.jpg",
    Name: "JOHN WICK 2",
    star: "7.5/10 ⭐",
    rotten: "89% 🍅",
    link: "",
  },
];
export default Data;
